"""Initial migration for PostgreSQL

Revision ID: 8bfd37a0a132
Revises: 
Create Date: 2025-11-12 16:42:11.977944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8bfd37a0a132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('video_info', sa.JSON(), nullable=True),
    sa.Column('basic_info', sa.JSON(), nullable=True),
    sa.Column('shot_table', sa.JSON(), nullable=True),
    sa.Column('golden_3s', sa.JSON(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('viral_formula', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('production_tips', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_id'), 'analysis_reports', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_video_url'), 'analysis_reports', ['video_url'], unique=True)
    op.create_table('hotspots',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('heat_score', sa.Integer(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('video_info', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_hotspots_id'), 'hotspots', ['id'], unique=False)
    op.create_index(op.f('ix_hotspots_match_score'), 'hotspots', ['match_score'], unique=False)
    op.create_index(op.f('ix_hotspots_platform'), 'hotspots', ['platform'], unique=False)
    op.create_index(op.f('ix_hotspots_title'), 'hotspots', ['title'], unique=False)
    op.create_table('live_rooms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('ip_character', sa.String(length=100), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_rooms_category'), 'live_rooms', ['category'], unique=False)
    op.create_index(op.f('ix_live_rooms_id'), 'live_rooms', ['id'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('live_room_id', sa.String(length=64), nullable=True),
    sa.Column('product_link', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('selling_points', sa.JSON(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('hand_card', sa.Text(), nullable=True),
    sa.Column('live_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['live_room_id'], ['live_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_live_date'), 'products', ['live_date'], unique=False)
    op.create_index(op.f('ix_products_live_room_id'), 'products', ['live_room_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('scripts',
    sa.Column('hotspot_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_report_id', sa.String(length=64), nullable=True),
    sa.Column('video_info', sa.JSON(), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('shot_list', sa.JSON(), nullable=True),
    sa.Column('production_notes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_report_id'], ['analysis_reports.id'], ),
    sa.ForeignKeyConstraint(['hotspot_id'], ['hotspots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_id'), 'scripts', ['id'], unique=False)
    op.create_index(op.f('ix_scripts_product_id'), 'scripts', ['product_id'], unique=False)
    op.create_index(op.f('ix_scripts_status'), 'scripts', ['status'], unique=False)
    # 注意：不删除其他项目的表（report_memory, projects, tasks, users, langgraph_checkpoints）
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：不恢复其他项目的表（langgraph_checkpoints, users, tasks, projects, report_memory）
    op.drop_index(op.f('ix_scripts_status'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_product_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_live_room_id'), table_name='products')
    op.drop_index(op.f('ix_products_live_date'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_live_rooms_id'), table_name='live_rooms')
    op.drop_index(op.f('ix_live_rooms_category'), table_name='live_rooms')
    op.drop_table('live_rooms')
    op.drop_index(op.f('ix_hotspots_title'), table_name='hotspots')
    op.drop_index(op.f('ix_hotspots_platform'), table_name='hotspots')
    op.drop_index(op.f('ix_hotspots_match_score'), table_name='hotspots')
    op.drop_index(op.f('ix_hotspots_id'), table_name='hotspots')
    op.drop_table('hotspots')
    op.drop_index(op.f('ix_analysis_reports_video_url'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###

